//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarlinApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManufacturer_tblProduct
    {
        public int Manufacturer_Id { get; set; }
        public int Product_Id { get; set; }
    
        public virtual tblManufacturer_tblProduct tblManufacturer_tblProduct1 { get; set; }
        public virtual tblManufacturer_tblProduct tblManufacturer_tblProduct2 { get; set; }
    }
}
