//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarlinApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblPropertyValues = new HashSet<tblPropertyValue>();
        }
    
        public int Product_ID { get; set; }
        public Nullable<int> Manufacturer_ID { get; set; }
        public Nullable<int> Sales_ID { get; set; }
        public Nullable<int> SubCategory_ID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Image { get; set; }
        public string Series { get; set; }
        public string Model { get; set; }
        public Nullable<int> Model_Year { get; set; }
        public string Series_Infro { get; set; }
        public Nullable<int> Document_ID { get; set; }
        public string Featured { get; set; }
        public Nullable<double> Price { get; set; }
        public string Brand { get; set; }
        public string Screen_Size { get; set; }
        public string RAM { get; set; }
        public string Processor_Model { get; set; }
        public string Storage_Type { get; set; }
        public string Operating_System { get; set; }
        public string Color { get; set; }
    
        public virtual tblDocument tblDocument { get; set; }
        public virtual tblManufacturer tblManufacturer { get; set; }
        public virtual tblSale tblSale { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPropertyValue> tblPropertyValues { get; set; }
    }
}
